### ISSUE TITLE
multiple PIE Items can be loaded on the same page

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-project#2]
Per discussion 10/6 the proposed approach is to use a scoping/namespacing mechanism when packaging so pie element and pie controllers can be connected.

**Comment by evaneus** [comment]
Maybe we should stick with the model of custom elements and make a `pie-controller` element to not pollute global scope?

For scoping and to avoid conflicts maybe should make the js files and element names with the packager?

e.g.

```
  pie-player-${itemId}.js
  pie-controller-${itemId}.js
```

(with ${itemId} derived from the directory name by default)

So a user/system would declare the html like:

(Assuming we have two items with the ids `zvjw5r` and `zvjj87`)

``` html
<script src="zvjw5r/pie-player-zvjw5r.js"></script>
<script src="zvjw5r/pie-controller-zvjw5r.js"></script>
<script src="zvjj87/pie-player-zvjj87.js"></script>
<script src="zvjj87/pie-controller-zvjj87.js"></script>

<pie-player-zvjw5r id="player-one">
  <pie-controller-zvjw5r></pie-controller>
</pie-player>

<pie-player-zvjj87 id="player-two">
  <pie-controller-zvjj87></pie-controller>
</pie-player>
```

**Comment by edeustace** [comment]
I'm not a fan of coupling an element to it's data, can't we just set a uid on the element tag that is used to look up the appropriate controller instance on the markup side:

```
<pie-player question-id="one"></pie-player>

<pie-player question-id="two"></pie-player>

<script>
  document.addEventListener('pie-player-ready', function(event){
    event.target.controller = pie.controllers[event.target.getAttribute('question-id')];
  });
</script>
```

On the packing side there'd be an option to specify a uid for the controller which would then be used to set the controller to `window.pie.controllers`?

**Comment by evaneus** [comment]
But what we're talking here is putting two fully independent PIE items in a page (Items that were not packaged together originally.)

Our packaged items - as currently defined - include the pie-player within them, so in this scenario you'd have two bundles declaring the same element:

```
<pie-player question-id="one"></pie-player>

<pie-player question-id="two"></pie-player>
```

Also not sure in that scenario how the controller gets itself into the map in `pie.controllers`

Seems like if we used a Custom Element for the controller we can leave the global scope clean?

**Comment by ghost** [comment]
Could we load the controller via some kind of require from inside the player?  

```
<script src="zvjw5r/pie-player-zvjw5r.js"></script>
<script src="zvjj87/pie-player-zvjj87.js"></script>

<pie-player-zvjw5r id="player-one">
</pie-player>

<pie-player-zvjj87 id="player-two">
</pie-player>
```

Also we could try to separate the static part of the player bundle from the varaible part so that the static part can be cached.

**Comment by edeustace** [comment]
I agree with @rbokel that what's static should be separate from what's variable. I don't think it's our role to agree a 'packed' format that allows this to happen. The packing we're doing at the moment is just one manifestation of using the `pie` format and we're defining this `pie` format in such a way that it won't prevent this use case.

Currently trying to get 2 packed questions to run on one page will lead to lot's of code duplication and element registration errors. If you really wanted to go down that road we'd have to assign uids to all the element definitions and not worry about that fact that there's a crazy amount of duplicated logic on the page.

If I wanted to build a server that allowed 2 players to run on the page I'd: 
- define the `pie-player`, `PieController`
- create a bundle of custom element definitions for all the elements needed
- create a controller map with all the logic needed
- create 2 different pie-player instances and inject a different controller instance to each of them

The goal of this is to remove duplication and reuse elements effectively. 

This isn't something that our 'packing' does, and I don't think it needs to do it, but the `pie` format would make this possible.

The idea of bundling everything into a custom player feels awkward.

**Comment by ghost** [comment]
Apparently you have to keep track of the registered elements. We could do that by using our own pie.registerElement method, which would have to maintain some kind of registry. 
Still that wouldn't solve the duplicate logic issue. Expanding on the idea of using require in the browser, we could load pies at runtime instead of bundling them?

**Comment by ghost** [comment]
With a packaged format there is also a good chance, that two packages contain different versions of the same things. Now it's getting nasty ;)

**Comment by evaneus** [comment]
Just to reset this discussion  - the issue may not be named appropriately to reflect the discussion that prompted it.

The actual question should be: is full self-encapsulation of PIEs possible (and reasonable to support without undue effort or effect on other parts of the spec). Not what is the optimal or most performant way to show more than one a page. There is no question that even if it is possible it would not be the most performant thing to do.

It's a fair point that if there are other Custom Elements within PIEs that there could be registration conflicts. Can't think of an easy way around it.

Re the browser loading thing @rbokel , I think we've looked at that and the issue, in this case, would remain that if the PIEs were not packaged with the intent of working together then it wouldn't help much. You can do completely unpackaged with SystemJS but that isn't really viable for production.

We should take this offline for now, and do a hangout.

**Comment by evaneus** [comment]
Closing this with the conclusion that we aren't trying to support this at the moment, if a user really wanted to do this (load separately packaged pie items in a page) they could use iframes. Otherwise the recommendation is that you package the PIEs you need together
