### ISSUE TITLE
rename and move core PIEs

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-project#20]
Our core PIEs need to be:

- moved to the PieElements org
- renamed to lose the *-react suffix
- published on NPM

should rename `corespring-multi-choice` to `corespring-choice`  it is not only multi choice

**Comment by edeustace** [comment]
https://github.com/PieElements

**Comment by edeustace** [comment]
@amiklosi is going to look after `corespring-placement-ordering`, I'm doing `corespring-choice`.
