### ISSUE TITLE
`env` property is available in Custom Elements

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-project#50]
(need to create issues to update pie-docs and pie-cli)

Custom Elements that do not implement a controller need to be able to react to the current context in the `env` property.

To achieve this we will add an `env` property to the Custom Element api that will be managed & updated by pie-player, and can be observed by the developer of the Custom Element.

**Comment by edeustace** [comment]
Coming in [pie-player v2.1.0](https://github.com/PieLabs/pie-player/pull/9)
