### ISSUE TITLE
remove vue example

### ISSUE THREAD

**Issue by edeustace** [PieLabs/pie-project#52]

**Comment by jmealo** [comment]
@edeustace We were planning on using Vue/Vuetify with the components if possible. We briefly played with Material Components (which on paper seems like the best fit for this library) but Vuetify had a better API for our purposes. I may be able to allocate some development resources to the pie-project. Can we sync up out of band to discuss? Thanks, Jeff

**Comment by evaneus** [comment]
hi @jmealo I do think it is worth a discussion as we're talking with some other organizations and hopefully will be collaborating soon on a pretty thorough set of OSS question types which may be relevant to you. We're also very open to continuing to support Vue as an implementation option and happy to chat with you about that. Can you reach out to me at evan@corespring.org ?
