### ISSUE TITLE
Value of  property  "lockChoiceOrder" and   "removeTilesAfterPlacing" are not getting update on checked or unchecked

### ISSUE THREAD

**Issue by paritoshcardinal** [PieLabs/pie-project#53]
I was trying to check or unchecked the  property  "lockChoiceOrder" and   "removeTilesAfterPlacing" of categories question but I all ways get default value i.e. false for both property on "model.updated" event. Even its get selected or deselected but its model values never get update. Please look into this issue ASAP.
![issue](https://user-images.githubusercontent.com/3908908/88200858-57335800-cc64-11ea-8eab-cd578aff7960.png)

**Comment by edeustace** [comment]
hi @paritoshcardinal - All the repos under the PieLabs org are no longer maintained. See https://github.com/pie-framework/pie-elements instead, this is where are actively developing the components. You should be able to find the same element in that repo.
